# Generated by Django 5.2.6 on 2025-09-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='picture',
            field=models.URLField(max_length=500),
        ),
    ]
